baseURL: https://aafu.pages.dev/
languageCode: ru
build:
  writeStats: true
params:
  title: Основы Информационной Безопасности
  author: Исаев Булат
  description: Website title
  copyright:
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  favicons:
    use: true

  profile:
    name: "Исаев Булат"
    tagline: НПИбд-01-22
    location: "Москва"
    photo: Photo.jpg
  showInAccordion:
    - item: aboutme
      expand: true
    - item: project
    - item: skill
  aboutme:
    title: Обо мне
    icon: fas fa-user
    description: Исаев Булат, группа НПИбд-01-22. Студенческий билет 1132227131
  project:
    title: Проект по прохождению внешнего курса "Основы кибербезопасности"
    icon: fas fa-project-diagram
    list:
      - title: Отчёт
        description: https://github.com/bulatisaev/OIB/blob/main/Vneshnie_Kursi/Report%20IBA.md

      - title: Аккаунт в Stepik (курс пройден 14.03.2024)
        description: https://stepik.org/users/800937467/profile
        
      - title: Прохождение курса "Основы кибербезопасности"
        description: https://www.youtube.com/playlist?list=PLee3XNDPQRkoa1gJHQ5VvW_OHQRDQSM-V

      - title: Фотография прохождения курса
        description: https://github.com/bulatisaev/OIB/blob/main/Vneshnie_Kursi/images/5.jpg
  skill:
    title: Моё обучение
    panelId: skill-panel
    icon: fas fa-cogs
    list:
      - skill: "Безопасность в сети"
        skillrating: 100
      - skill: "Защита ПК/Телефона"
        skillrating: 100
      - skill: "Криптография на практике"
        skillrating: 100

